import numpy as np
import matplotlib.pyplot as plt

"""
pi_approximations = np.loadtxt("pi_iterations")

plt.plot(pi_approximations)
plt.xlabel("Iteration")
plt.ylabel("Approximation of π")
plt.savefig("plot.png")  
"""

avg_sqr_mag_L6 = np.loadtxt("iterations/sqr_avg_mag_vsT_L6.txt")
avg_sqr_mag_L8 = np.loadtxt("iterations/sqr_avg_mag_vsT_L8.txt")
avg_sqr_mag_L10 = np.loadtxt("iterations/sqr_avg_mag_vsT_L10.txt")
avg_sqr_mag_L12 = np.loadtxt("iterations/sqr_avg_mag_vsT_L12.txt")
avg_E_L6 = np.loadtxt("iterations/avg_E_vsT_L6.txt")
avg_E_L8 = np.loadtxt("iterations/avg_E_vsT_L8.txt")
avg_E_L10 = np.loadtxt("iterations/avg_E_vsT_L10.txt")
avg_E_L12 = np.loadtxt("iterations/avg_E_vsT_L12.txt")
autocorr_L6 = np.loadtxt("iterations/autocorr_mag_L6.txt")
autocorr_L8 = np.loadtxt("iterations/autocorr_mag_L8.txt")
autocorr_L10 = np.loadtxt("iterations/autocorr_mag_L10.txt")
autocorr_L12 = np.loadtxt("iterations/autocorr_mag_L12.txt")
Cv_vsT_L6 = np.loadtxt("iterations/Cv_vsT_L6.txt")
Cv_vsT_L8= np.loadtxt("iterations/Cv_vsT_L8.txt")
Cv_vsT_L10 = np.loadtxt("iterations/Cv_vsT_L10.txt")
Cv_vsT_L12 = np.loadtxt("iterations/Cv_vsT_L12.txt")
binder_vsT_L6 = np.loadtxt("iterations/binder_vsT_L6.txt")
binder_vsT_L8 = np.loadtxt("iterations/binder_vsT_L8.txt")
binder_vsT_L10 = np.loadtxt("iterations/binder_vsT_L10.txt")
binder_vsT_L12 = np.loadtxt("iterations/binder_vsT_L12.txt")

T0 = 1.5
dT = 0.1

temps = T0 + dT * np.arange(len(avg_sqr_mag_L6))

plt.figure(1)
plt.plot(temps, avg_sqr_mag_L6, marker='o', linestyle='-', color='blue', label = "L = 6")
plt.plot(temps, avg_sqr_mag_L8, marker='o', linestyle='-', color='orange', label = "L = 8")
plt.plot(temps, avg_sqr_mag_L10, marker='o', linestyle='-', color='green', label = "L = 10")
plt.plot(temps, avg_sqr_mag_L12, marker='o', linestyle='-', color='red', label = "L = 12")

plt.xlabel("Temperature T")
plt.ylabel(r"$\langle m^2 \rangle$")
plt.title("Squared Magnetization vs Temperature")
plt.grid(True)

plt.legend()  
plt.savefig("plot_avg_sqr_mag.png")

plt.figure(2)
plt.plot(temps, avg_E_L6, marker='o', linestyle='-', color = 'blue', label = "L = 6")
plt.plot(temps, avg_E_L8, marker='o', linestyle='-', color = 'orange', label = "L = 8")
plt.plot(temps, avg_E_L10, marker='o', linestyle='-', color = 'green', label = "L = 10")
plt.plot(temps, avg_E_L12, marker='o', linestyle='-', color = 'red', label = "L = 12")
plt.xlabel("Temperature T")
plt.ylabel(r"$\langle E \rangle$")
plt.title("Energy vs Temperature")
plt.grid(True)
plt.legend()
plt.savefig("plot_energy.png")

plt.figure(3)
plt.plot(np.arange(1000), autocorr_L6, linestyle='-', color = 'blue', label = "L = 6")
plt.plot(np.arange(1000), autocorr_L8, linestyle='-', color = 'orange', label = "L = 8")
plt.plot(np.arange(1000), autocorr_L10, linestyle='-', color = 'green', label = "L = 10")
plt.plot(np.arange(1000), autocorr_L12, linestyle='-', color = 'red', label = "L = 12")
plt.xlabel(r"$\tau$")
plt.ylabel(r"$C_{m^2} (\tau)$")
plt.grid(True)
plt.legend()
plt.savefig("autocorrelation.png")

plt.figure(4)
plt.plot(temps, Cv_vsT_L6, linestyle='-', color = 'blue', label = "L = 6")
plt.plot(temps, Cv_vsT_L8, linestyle='-', color = 'orange', label = "L = 8")
plt.plot(temps, Cv_vsT_L10, linestyle='-', color = 'green', label = "L = 10")
plt.plot(temps, Cv_vsT_L12, linestyle='-', color = 'red', label = "L = 12")
plt.xlabel("temperature T")
plt.ylabel(r"$C_{v}$")
plt.grid(True)
plt.legend()
plt.savefig("specific_heat_per_spin.png")

plt.figure(5)
plt.plot(temps, binder_vsT_L6, linestyle='-', color = 'blue', label = "L = 6")
plt.plot(temps, binder_vsT_L8, linestyle='-', color = 'orange', label = "L = 8")
plt.plot(temps, binder_vsT_L10, linestyle='-', color = 'green', label = "L = 10")
plt.plot(temps, binder_vsT_L12, linestyle='-', color = 'red', label = "L = 12")
plt.xlabel("temperature T")
plt.ylabel("b")
plt.grid(True)
plt.legend()
plt.savefig("binder_cumulant_vsT.png")